# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: SCALES Documentation

theme: 
  name: material
  features:
    - navigation.tabs
    - header.autohide
    - navigation.path
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: Images/SCALES Mission Patch.png
  favicon: Images/SCALES Mission Patch.png

plugins:
  - search  # To have search functionality on the document
  #- mkdocs-pdf #PDF Embed Ability

markdown_extensions:
  - attr_list
  - md_in_html
  - attr_list
  - abbr
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.pathconverter:
      base_path: 'DOCUMENTATION' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: 
    - Welcome: index.md
    - Hardware: hardware_home.md
    - Software: software_home.md
    - Testing: testng_home.md
    
  - Hardware:
    - Hardware Home: hardware_home.md
    - SCALES Compute Module: imx8x_merger.md
    - Peripheral Board: peripheral_board.md
    - Nvidia Jetson Orin AGX: nvidia_jetson_orin_agx.md
  - Software:
    - Software Home: software_home.md
    - Build the i.MX 8X Yocto BSP: imx_yocto_bsp.md
    - How to Create and Maintain a Custom BSP for the IMX8X: IMX8X_customBSP.md
    - SCALES Demo: scales_demo.md
  - Testing: 
    - Testing Home: testing_home.md
    - Test Procedure for i.MX and VOXL: Test Procedure List.md
    - Jetson Inference Performance: ML_Jetson_Performance.md
    - Jetson Training Performance : ML_Training.md 

extra:
  social:
    - icon: material/github 
      link: https://github.com/BroncoSpace-Lab
